Skillz/Models/Car.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Skillz.Models
{
    public class Car
    {
        [Key, Column("Id")]
        public int Id { get; set; }
        [Required]
        public string Make { get; set; }
        [Required]
        public string Model { get; set; }
        [Required]
        public string Color { get; set; }
        [Required]
        public int Price { get; set; }
        [Required, Display(Name = "Trim Level")]
        public string TrimLevel { get; set; }
        public bool IsDeleted { get; set; }
    }
    public class CarContext : DbContext
    {
        public DbSet<Car> Cars { get; set; }
    }
}

Skillz/Controllers/BaseController.cs
using Skillz.Utils;
using System.Web.Mvc;

namespace Skillz.Controllers
{
    public class BaseController : Controller 
    {
        protected JavascriptViewResult JavascriptView(string viewName)
        {
            return JavascriptView(viewName, null);
        }

        protected JavascriptViewResult ReplaceHtml(string selector, string viewName, object model,
            bool showAlerts = true)
        {
            var replaceHtmlViewModel = new ReplaceHtmlViewModel
            {
                Model = model,
                ShowAlerts = showAlerts,
                Selector = selector,
                ViewName = viewName
            };
            return JavascriptView("_ReplaceHtml.js", replaceHtmlViewModel);
        }

        protected JavascriptViewResult JavascriptView(string viewName, object model)
        {
            if (model != null)
                ViewData.Model = model;
            var javascriptViewResult = new JavascriptViewResult
            {
                ViewName = viewName,
                ViewData = ViewData,
                TempData = TempData,
                ViewEngineCollection = ViewEngineCollection
            };
            return javascriptViewResult;
        }
    }
}

Skillz/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Skillz.Controllers
{
    public class DefaultController : BaseController
    {
        private Models.CarContext db;
        public DefaultController(Models.CarContext dbContext)
        {            
            this.db = dbContext;
        }

        public DefaultController()
        {
            this.db = new Models.CarContext();
        }

        [HttpGet]
        public ActionResult Index(bool showDeleted = false)
        {
            ViewBag.ShowDeleted = showDeleted;
            using (db)
            {
                IQueryable<Models.Car> cars = showDeleted ? db.Cars : db.Cars.Where(x=> !x.IsDeleted);
                var sortedCars = cars.OrderBy(x => x.IsDeleted).ToList();
                if (Request.IsAjaxRequest())
                    return ReplaceHtml("#carsList", "_CarsList", sortedCars);
                return View(sortedCars);
            }
        }

        public ActionResult Create()
        {
            return View("Edit");
        }

        [HttpPost]
        public ActionResult Create(Models.Car frank)
        {
            if (!ModelState.IsValid) return View("Edit", frank);
            using (db)
            {
                db.Cars.Add(frank);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            using (db)
            {
                var car = db.Cars.SingleOrDefault(x => x.Id == id);
                if (car == null)
                    return RedirectToAction("Index");
                return View(car);
            }
        }
        [HttpPost]
        public ActionResult Edit(int id, Models.Car frank)
        {
            if (!ModelState.IsValid) return View("Edit", frank);
            using (db)
            {
                db.Cars.AddOrUpdate(frank);
                db.SaveChanges();
            }
            return RedirectToAction("Edit", new { id });
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            using (db)
            {
                var car = db.Cars.Single(x => x.Id == id);
                car.IsDeleted = true;
                db.SaveChanges();
            }
            return Content("OK");// RedirectToAction("Index");
        }
    }
}

Skillz/Views/Default/Edit.cshtml
@model Skillz.Models.Car
@{
    var isNew = Model == null || Model.Id == 0;
    ViewBag.Title = isNew ? "Add Car" : "Edit Car";
}

<a href="@Url.Action("Index")" class="mb-2 btn btn-outline-secondary"><i class="fa fa-chevron-left"></i> Back to Cars</a>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @if (!isNew)
    {
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.IsDeleted)
    }

    <div class="form-row">
        <div class="form-group col-md-3">
            @Html.LabelFor(model => model.Make, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.Make, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Make, "", new { @class = "text-danger" })
        </div>
        <div class="form-group col-md-3">
            @Html.LabelFor(model => model.Model, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-3">
            @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
        </div>
        <div class="form-group col-md-3">
            
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label" })
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text">$</span>
                </div>
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                <div class="input-group-append">
                    <span class="input-group-text">.00</span>
                </div>
            </div>
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
        <div class="form-group col-md-3">
            @Html.LabelFor(model => model.TrimLevel, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.TrimLevel, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TrimLevel, "", new { @class = "text-danger" })
        </div>
    </div>


    <button type="submit" class="btn btn-primary">
        @(isNew ? "Add" : "Save")
    </button>
</div>
}

Skillz/Views/Default/Index.cshtml
@model IEnumerable<Skillz.Models.Car>

@{
    ViewBag.Title = "Cars";
    bool showDeleted = ViewBag.ShowDeleted;
}
@section scripts{
    <script>
        $(document).ready(function () {
            $(document).on('click', '[data-delete-url]', deleteCar);
        });
        function deleteCar(e) {
            e.preventDefault();
            var url = $(this).data('delete-url')// @*'@Url.Action("Delete")?id=' + id;*@
            $.post(url).done(function () {
                $.getScript('@Url.Action("Index")?showDeleted=@showDeleted').error(function(e) {
				    if (e.status === 404) {
					    $('#carsList').html('<div class="alert alert-info" style="padding: 5px 10px;">' + e.statusText + '</div>');
				    } else {
					    $('#carsList').html('<div class="alert alert-danger" style="padding: 5px 10px;">Error loading cars</div>');
				    }
			    });
            });

        }
    </script>
}
<p>
    @Html.ActionLink("Add New Car", "Create", null, new { @class = "btn btn-primary" })
    @Html.ActionLink("Show All", "Index", new { showDeleted = true }, new { @class = "btn btn-secondary" })
</p>
<div id="carsList">
    @Html.Partial("_CarsList", Model)
</div>

Skillz/Views/Default/_CarsList.cshtml
@model IEnumerable<Skillz.Models.Car>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.Make)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.Model)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.Color)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.Price)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.TrimLevel)
    </th>
    <th></th>
</tr>
@if (!Model.Any())
{
    <tr>
        <td colspan="42">No cars, yet!</td>
    </tr>
}
@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Make)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Model)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Color)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TrimLevel)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-secondary" })
            @if (!item.IsDeleted)
            {
                <button data-delete-url="@Url.Action("Delete", "Default", new { id = item.Id })" type="button" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this record?')">Delete</button>
            }
            else
            {
                <span class="badge badge-danger">Deleted</span>
            }
        </td>
    </tr>
}

</table>

Skillz/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link href="https://fonts.googleapis.com/css?family=Bangers&display=swap" rel="stylesheet">
    <title>@ViewBag.Title</title>
    <style>
        body {
            background-color: #333;
        }
        label, table, table tr td, table tr th {
            color: #fff;
        }
    </style>
</head>
<body>
    <div class="container" id="main">
        <div class="mb-2 mt-1">
            <h1 style="font-family:'Bangers';font-size:100px; text-align:center;">
            <a style="color: #fff" href="@Url.Action("Index", "Default")">
                Carapolooza!
            </a></h1>
        </div>
        @RenderBody()
    </div>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    @RenderSection("scripts", false)
</body>
</html>

Skillz/Views/Shared/_ReplaceHtml.js.cshtml
@using Skillz.Utils
@model ReplaceHtmlViewModel
$('@Model.Selector').html('@(Html.Raw(HttpUtility.JavaScriptStringEncode(Html.Partial(Model.ViewName, Model.Model).ToString())))');